### ISSUE TITLE
flaky test ServerThrowsHubExceptionOnStreamingHubMethodArgumentCountMismatch

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1673]
```
Failed   Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.ServerThrowsHubExceptionOnStreamingHubMethodArgumentCountMismatch(hubProtocol: JsonHubProtocol { Name = "json", PayloadSerializer = JsonSerializer { Binder = (throws InvalidOperationException), CheckAdditionalContent = False, ConstructorHandling = Default, Context = System.Runtime.Serialization.StreamingContext, ContractResolver = CamelCasePropertyNamesContractResolver { ... }, ... }, TransferFormat = Text }, transportType: LongPolling, hubPath: "/dynamic")
Error Message:
 Assert.Throws() Failure
Expected: typeof(Microsoft.AspNetCore.SignalR.Client.HubException)
Actual:   typeof(System.OperationCanceledException): Invocation terminated
Stack Trace:
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.<>c__DisplayClass57_0`1.<<StreamAsChannelAsync>g__RunChannel|0>d.MoveNext() in /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnectionExtensions.StreamAsync.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at System.Threading.Channels.ChannelExtensions.ReadAllAsync[T](ChannelReader`1 channel) in /Users/dfowler/dev/SignalR/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ChannelExtensions.cs:line 14
   at System.Threading.Tasks.TaskExtensions.OrTimeout[T](Task`1 task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber) in /Users/dfowler/dev/SignalR/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs:line 58
Standard Output Messages:
 | TestLifetime Information: Starting test ServerThrowsHubExceptionOnStreamingHubMethodArgumentCountMismatch_json_LongPolling_dynamic
 | Microsoft.AspNetCore.Sockets.Client.LongPollingTransport Information: Starting transport. Transfer mode: Text.
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'json'.
 | Microsoft.AspNetCore.SignalR.Client.HubConnection Error: Server returned handshake error: An unexpected error occurred during connection handshake. InvalidDataException: Missing required property 'protocol'.
 | Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Error: Exception from test
 | Expected: typeof(Microsoft.AspNetCore.SignalR.Client.HubException)
 | Actual:   typeof(System.OperationCanceledException): Invocation terminated
 |    at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
 |    at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.<>c__DisplayClass57_0`1.<<StreamAsChannelAsync>g__RunChannel|0>d.MoveNext() in /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnectionExtensions.StreamAsync.cs:line 84
 | --- End of stack trace from previous location where exception was thrown ---
 |    at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
 |    at System.Threading.Channels.ChannelExtensions.ReadAllAsync[T](ChannelReader`1 channel) in /Users/dfowler/dev/SignalR/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ChannelExtensions.cs:line 14
 |    at System.Threading.Tasks.TaskExtensions.OrTimeout[T](Task`1 task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber) in /Users/dfowler/dev/SignalR/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs:line 58
 |    at Xunit.Assert.RecordExceptionAsync(Func`1 testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\Record.cs:line 82
 | Microsoft.AspNetCore.Sockets.Client.HttpConnection Information: Disposing client.
 | TestLifetime Information: Finished test ServerThrowsHubExceptionOnStreamingHubMethodArgumentCountMismatch_json_LongPolling_dynamic in 0.025647s
```

Seems like we've reached a new level of flaky.

/cc @JamesNK

**Comment by BrennanConroy** [comment]
Did this happen on your machine? The TC CI has never seen a failure for these tests, and I've never seen it on Appveyor or Travis

**Comment by davidfowl** [comment]
I saw this on travis twice. Once in my PR once in an @anurse PR. We need to dump more useful information on the server. It'll make diagnosing this sorta issue easier

**Comment by davidfowl** [comment]
```
not ok 79 hubConnection over LongPolling transport can connect to hub with authorization
  ---
    - messages:
      - message: Expected Error: Server returned handshake error: An unexpected error occurred during connection handshake. InvalidDataException: Missing required property 'protocol'. to be undefined.
        operator: toBe
        actual: Error: Server returned handshake error: An unexpected error occurred during connection handshake. InvalidDataException: Missing required property 'protocol'.
      - message: Failed: Server returned handshake error: An unexpected error occurred during connection handshake. InvalidDataException: Missing required property 'protocol'.
    - logs:
      - level: Information
        message: Normalizing '/authorizedhub' to 'http://127.0.0.1:58149/authorizedhub'.
      - level: Trace
        message: Starting HubConnection.
      - level: Trace
        message: Starting connection with transfer format 'Text'.
      - level: Trace
        message: Sending negotiation request: http://127.0.0.1:58149/authorizedhub/negotiate
      - level: Trace
        message: Skipping transport 'WebSockets' because it was disabled by the client.
      - level: Trace
        message: Skipping transport 'ServerSentEvents' because it was disabled by the client.
      - level: Trace
        message: Selecting transport 'LongPolling'
      - level: Trace
        message: (LongPolling transport) Connecting
      - level: Trace
        message: (LongPolling transport) polling: http://127.0.0.1:58149/authorizedhub?id=qhkol-W3YHcm6HuGn8Qd7g&_=1522736688725
      - level: Trace
        message: Sending handshake request.
      - level: Trace
        message: (LongPolling transport) sending data. String data of length 32.
      - level: Trace
        message: (LongPolling transport) request complete. Response status: 200.
      - level: Information
        message: Using HubProtocol 'json'.
      - level: Trace
        message: (LongPolling transport) sending data. String data of length 69.
      - level: Trace
        message: (LongPolling transport) request complete. Response status: 200.
      - level: Trace
        message: (LongPolling transport) data received. String data of length 130.
      - level: Error
        message: Server returned handshake error: An unexpected error occurred during connection handshake. InvalidDataException: Missing required property 'protocol'.
      - level: Trace
        message: (LongPolling transport) polling: http://127.0.0.1:58149/authorizedhub?id=qhkol-W3YHcm6HuGn8Qd7g&_=1522736688754
      - level: Error
        message: Connection disconnected with error 'Error: Server returned handshake error: An unexpected error occurred during connection handshake. InvalidDataException: Missing required property 'protocol'.'
```

This is after running the client side tests in a loop
