### ISSUE TITLE
not ok 70 hubConnection using messagepack over LongPolling transport can receive server calls

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1817]
not ok 70 hubConnection using messagepack over LongPolling transport can receive server calls

```
    ---
      - messages:
        - message: Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      - logs: 
        - level: Information
          message: Normalizing '/testhub' to 'http://127.0.0.1:36578/testhub'.
        - level: Trace
          message: Starting HubConnection.
        - level: Trace
          message: Starting connection with transfer format 'Binary'.
        - level: Trace
          message: Sending negotiation request: http://127.0.0.1:36578/testhub/negotiate
        - level: Trace
          message: Skipping transport 'WebSockets' because it was disabled by the client.
        - level: Trace
          message: Skipping transport 'ServerSentEvents' because it was disabled by the client.
        - level: Trace
          message: Selecting transport 'LongPolling'
        - level: Trace
          message: (LongPolling transport) Connecting
        - level: Trace
          message: (LongPolling transport) polling: http://127.0.0.1:36578/testhub?id=4RPGdgXIXagAf2ds-30jrg&_=1522570781548
        - level: Trace
          message: Sending handshake request.
        - level: Trace
          message: (LongPolling transport) sending data. String data of length 39.
        - level: Trace
          message: (LongPolling transport) request complete. Response status: 200.
        - level: Information
          message: Using HubProtocol 'messagepack'.
        - level: Trace
          message: (LongPolling transport) sending data. Binary data of length 42.
        - level: Trace
          message: (LongPolling transport) request complete. Response status: 200.
    ...
```
