### ISSUE TITLE
Flaky test: hubConnection over LongPolling it sends DELETE request and waits for poll to terminate

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#2163]
Seen in this PR https://github.com/aspnet/SignalR/pull/2162

```
not ok 90 hubConnection over LongPolling it sends DELETE request and waits for poll to terminate
    ---
      - messages:
        - message: Failed: Not Found
      - logs: 
        - level: Information
          timestamp: 2018-04-29T21:20:21.069Z
          message: Normalizing '/testhub' to 'http://127.0.0.1:4437/testhub'.
        - level: Debug
          timestamp: 2018-04-29T21:20:21.069Z
          message: Starting HubConnection.
        - level: Debug
          timestamp: 2018-04-29T21:20:21.069Z
          message: Starting connection with transfer format 'Text'.
        - level: Debug
          timestamp: 2018-04-29T21:20:21.069Z
          message: Sending negotiation request: http://127.0.0.1:4437/testhub/negotiate
        - level: Debug
          timestamp: 2018-04-29T21:20:21.074Z
          message: Skipping transport 'WebSockets' because it was disabled by the client.
        - level: Debug
          timestamp: 2018-04-29T21:20:21.074Z
          message: Skipping transport 'ServerSentEvents' because it was disabled by the client.
        - level: Debug
          timestamp: 2018-04-29T21:20:21.074Z
          message: Selecting transport 'LongPolling'
        - level: Trace
          timestamp: 2018-04-29T21:20:21.075Z
          message: (LongPolling transport) Connecting
        - level: Trace
          timestamp: 2018-04-29T21:20:21.075Z
          message: (LongPolling transport) polling: http://127.0.0.1:4437/testhub?id=FfLyq9LR2aS8iZYv_YA1dQ&_=1525036821075
        - level: Trace
          timestamp: 2018-04-29T21:20:21.080Z
          message: (LongPolling transport) polling: http://127.0.0.1:4437/testhub?id=FfLyq9LR2aS8iZYv_YA1dQ&_=1525036821080
        - level: Debug
          timestamp: 2018-04-29T21:20:21.080Z
          message: Sending handshake request.
        - level: Trace
          timestamp: 2018-04-29T21:20:21.080Z
          message: (LongPolling transport) sending data. String data of length 32. Content: '{"protocol":"json","version":1}'..
        - level: Trace
          timestamp: 2018-04-29T21:20:21.084Z
          message: (LongPolling transport) request complete. Response status: 200.
        - level: Information
          timestamp: 2018-04-29T21:20:21.084Z
          message: Using HubProtocol 'json'.
        - level: Debug
          timestamp: 2018-04-29T21:20:21.085Z
          message: Stopping HubConnection.
        - level: Trace
          timestamp: 2018-04-29T21:20:21.085Z
          message: (LongPolling transport) sending DELETE request to http://127.0.0.1:4437/testhub?id=FfLyq9LR2aS8iZYv_YA1dQ.
        - level: Trace
          timestamp: 2018-04-29T21:20:21.088Z
          message: (LongPolling transport) Poll errored after shutdown: Not Found
        - level: Trace
          timestamp: 2018-04-29T21:20:21.088Z
          message: (LongPolling transport) Firing onclose event. Error: <undefined>
        - level: Information
          timestamp: 2018-04-29T21:20:21.089Z
          message: Connection disconnected.
        - level: Trace
          timestamp: 2018-04-29T21:20:21.089Z
          message: (LongPolling transport) Transport finished.
        - level: Trace
          timestamp: 2018-04-29T21:20:21.091Z
          message: (LongPolling transport) DELETE request accepted.
    ...
```

We should fix the ts client to do what the .NET client does and send the delete after the poll ends:
- Don't wait on the poll to terminate 
- Send delete after ending the poll

https://github.com/aspnet/SignalR/commit/d6395a52bc2de85d9513cb45cba3d9113c4d2a60#diff-ebcecff777de2ec17e8b72d021570c85
